# Generated by Django 5.2 on 2025-04-29 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_reservation_member_email_reservation_member_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='accommodation',
            name='universities',
            field=models.ManyToManyField(related_name='accommodations', to='accommodation.university'),
        ),
        migrations.AddField(
            model_name='notification',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accommodation.university'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='accommodation.university'),
        ),
    ]
