# Generated by Django 5.2 on 2025-04-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0003_university_accommodation_universities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
    ]
